### PR TITLE
Rank Maximal Matching Algorithm

### PR DESCRIPTION
**Pull request by oriyalperin**
Hello,

I'm a research assistant working with @erelsgl, and he has directed me to this repository.
I'd like to propose an initial version of a new algorithm page for your consideration.

The algorithm, "Rank Maximal Matching", is particularly useful in cases where applicants rank posts, with the goal of maximizing the number of applicants matched to their first-choice post, while also ensuring that the maximum possible number of applicants are matched to their second-choice post, and so on.

I'm here to contribute this algorithm page to your application.
Your feedback and collaboration on this addition would be greatly appreciated.

Thank you! :)

### CODE REVIEW

**Comment by erelsgl** [comment]
What is the netlify bot?
Where can we see the logs, to understand why the deploy failed?

The "Details" link leads to a page that says "please see the logs". Clicking the link to "the logs" leads to a page on on https://app.netlify.com website saying "page not found".

**Comment by JThh** [comment]
Thanks for your contribution! Please ignore the comments from the Netlify bot; I will deploy the app on the `dev` branch and test it first before we merge the branch into `new_main` which holds the current app codes.

**Review by JThh — APPROVED** [review]
Looks good. But I will test its deployment first for any unforeseen bugs.

**Comment by oriyalperin** [comment]
Amazing! thank you :)

**Pull request merged**
