### PR TITLE
Iterated Maximum Matching

### PR DESCRIPTION
**Pull request by oriyalperin**
Hi @JThh,
We've added another algorithm page. Let us know if any additions or changes are needed.
Thanks!

### CODE REVIEW

**Comment by JThh** [comment]
Thanks @oriyalperin! Really interesting work. Kindly allow me some time to go through some manual testing before I merge it into production branch.

**Comment by JThh** [comment]
Just note that `fairpyx` installation would require `Python >=3.9`.

**Comment by JThh** [comment]
The app looks great and it seems to be very useful.

It'd be great if the below points can be resolved:

0. That's more interesting if we can provide an option to run all algorithms and hold outcome summaries in a single table for easier comparison between methods;
1. We can make the three file uploads on the same row;
2. Since the app is meant for courses and students, we possibly rename agents to students and items to courses for clarity;
3. We can make some explanation in a separate section as in the first 3 apps about the meanings of the allocation and associated measures (e.g. `Utilitarian value`, `Egalitarian value`, measurements of `max envy` and `mean envy`);
4. Add spaces before and after the `/` in `items_capacities/agents_capacities/preferences` for line breaking;
5. The table entries are not restricted by the range you enforced (e.g. item capacity should be at least 10, but right now I can set it as 1);
6. Make this app appear before the `Create your own app`.
7. We may want to give proper credit to `fairpyx` about using their algorithm implementations.

If you have time, you may adjust the above (and others you noticed) by contributing to the `dev` branch; otherwise, I should be able to help as well (on some functionalities such as point `0`).

**Comment by oriyalperin** [comment]
Thanks for the feedback!
Regarding the first point, I tried to implement but the table is hard to read.
Do you think having separate tables for each algorithm might work better?

**Comment by JThh** [comment]
Sure!

**Pull request merged**
