### PR TITLE
Rank Maximal Matching Algorithm

### PR DESCRIPTION
**Pull request by JThh**
This PR is the actual deployment request from @oriyalperin and @erelsgl. The test app is available at https://fair-alloc-app-ra-7h8nhfqiswwfe2qrkksckj.streamlit.app/Rank_Maximal_Matching. 

It looks great to me. Thanks for your contribution! 

The original PR is at #4 .

### CODE REVIEW

**Comment by JThh** [comment]
Dear @oriyalperin  and @erelsgl, if all looks fine to you, I will merge the request and make it live on our app: https://fair-alloc.streamlit.app/.

**Comment by JThh** [comment]
Plus @oriyalperin, would you mind adding an **information tab** as we have done for our previous apps, as shown in the image below? It would be great if you could _explain a bit about the concept of Rank Maximal Matching, before giving a description of the algorithm you implemented with a proper citation_. Thank you!

Additionally, it would also be great if you could adjust the sidebar image size to match those of previous apps for better aesthetics. Thanks!

**Comment by JThh** [comment]
Screenshot 2023-10-28 at 13 27 31

If you need any help with writing, please let me know!

**Comment by oriyalperin** [comment]
Yes, it looks great, but we encountered an issue with the algorithm imported from the [networkz ](https://github.com/ariel-research/networkz) dependency.
I've resolved the problem; however, `networkz` version should now be updated to at least 1.0.6.

I'll also proceed with implementing the adjustments you've requested. Thanks again!

**Comment by erelsgl** [comment]
We have made some changes to the information card here: https://github.com/oriyalperin/fair-alloc-app-ra/tree/rmm  How do we move them to the present PR?

**Comment by JThh** [comment]
Thanks. Please help create a temporary PR for the dev branch (`rmm` to `dev` as in this #4 ).

**Comment by JThh** [comment]
LGTM and again thanks for your efforts! @oriyalperin and @erelsgl

**Comment by JThh** [comment]
The application should now be live at https://fair-alloc.streamlit.app/.

**Comment by oriyalperin** [comment]
Amazing, thank you!

**Pull request merged**
