### PR TITLE
Course Allocation Algorithms

### PR DESCRIPTION
**Pull request by oriyalperin**
Hi, I've implemented your suggestions from #11 in this PR.
Please let me know if anything is missing.
Thanks!

### CODE REVIEW

**Comment by oriyalperin** [comment]
Hi @JThh, just reminding you about this PR.
Appreciate your time!

**Comment by JThh** [comment]
Sorry for my late reply. Getting to it now!

**Comment by JThh** [comment]
Looks pretty good on my local machine. Thanks so much for your efforts!

I'm gonna merge it to the main branch in a bit!

**Comment by JThh** [comment]
Now up at: https://fair-alloc.streamlit.app/Course_Allocation_Problem.

**Pull request merged**
